### PR TITLE
Teams/Groups feature

### LINKED ISSUE #8: Teams
Hello
nice package. would it be possible to add a "Teams" or "Workspaces" a la spark on top of roles ?
For my saas project i would need a user-teams role definition so that I can have administrators, team administrators and members roles for each team. Permissions would be declared one time only like read, write, updated, delete, etc ... and would be reusable across roles. So one user could have many teams and in each team it would have different roles, connected with different permissions.
I'm asking instead of doing because i'm not sure how to figure it out.
have nice day
Francois

### LINKED ISSUE #540: Group Permissions Support
Hi,
Does this package have support for group permissions or teams? where i can assign permissions to a group like the one in laratrust (https://github.com/santigarcor/laratrust) package?

### LINKED ISSUE #551: User with multiple roles per team
Hi,

My user can be part of multiple teams and can have different roles for each team. I have set a many-to-many relationship between team and user model with `user_team` pivot table. Is there any option to add roles to this `user_team` table so that user can have different roles in each team?

Any guidance in this respect is welcome. 

Regards
Sam

### LINKED ISSUE #1067: Give permissions/roles based on multiple accounts
Is there a way to give a permission/role to a user when using a multiple level account system.

Example:

Account 1
-- User 1 [Admin]
-- User 2 [Editor]

Account 2
-- User 1 [Editor]

The user is able to swap accounts during their session.

### LINKED ISSUE #1135: Laravel Roles and Permissions with parameters
I am planning on extending a system that helps me mark students off in lab classes of various courses that they are enrolled in. I have a basic version of the system working, but it needs a better permission system.

I have users and courses. What I want is the ability to have roles such as "Coordinator" and "Grader" but based on a course.

So a particular user might be a "Grader on Course1" and a "Coordinator on Course2"

The role of "Grader on Course X" would have underlying permissions of "Can view Course X", "Can Grade Course X" etc. "Coordinator on Course X" might have other permissions such as "Can enroll students on Course X".

So my roles and permissions are sort of parameterized by courses.

With spatie/laravel-permission I understand that I can make roles such as Grader and Coordinator (along with the underlying permissions). But that would not allow me to make a particular user a Grader on one course but not all the others.

Combining this package (spatie/laravel-permission) with Laravels policies I think I get closer. The policies are parameterized by models (i.e., the Course model in my case). But I don't understand how the policies would tie in with the roles and permissions unless they are too parameterized.

Any ideas on the best way to solve this?

One way I thought of was to have roles such as "coordinator_course1", "coordinator_course2", "coordinator_course3" ... and permissions such as "can_view_course1", "can_view_course2", "can_view_course3", ... But this feels like a poor choice.

Any advice would be most welcome.

### LINKED ISSUE #1186: Scope/Policy to limit database results to what the user is authorized for
Hi,

I have a model in my application for which users have to be specifically authorized to be able to see them and I'm trying to come up with an application-wide method to limit database results for this model to only those that the user is allowed to access. For example, a user would have to have a permission called `view post {id}`, or a permission called `view post` with `post {id}` as the guard name. The user could also have a `view all posts` permission that allows them to view every post. Since I'm using repository classes to access my models, instead of directly, I'd like this to be global for my application. I'd also like pagination to keep working.

I've tried several approaches but I can't really figure it out. I initially tried a policy:

```php
public function view(User $user, Post $post)
{
  // Using direct permissions
  $user->hasPermissionTo('view post ' . $post->id);

  // Using guards
  $user->hasPermissionTo('view post', 'post ' . $post->id);
}
```

This does not work at all for some reason, even though I made sure to register the policy in the `AuthServiceProvider` (bound to the model).

Then I tried a global scope:

```php
class Post extends Model
{
  protected static function boot()
  {
    parent::boot();

    static::addGlobalScope(function (Builder $builder) {
      // This $builder instance is for the `posts` table and has nothing to do with
      // permissions or the currently logged in user.
    });
  }
}
```

As demonstrated above, I don't know how to add a constraint to the `Builder` instance that is provided to limit the results to the results the user is authorized for. So I'm not sure this is the way to go either.

Does anyone have any suggestions on what would be the best way to approach this?
Thanks in advance!

### LINKED ISSUE #1187: Granular Permissions
Consider software that allows users to share files with other individual users within the same organisation. (Not Multi-tenant)

There does not seem like there is a simple way to discriminantly share certain files with certain users with a specific permission. 
User 1, allows User 2, to [read|write|delete] File 1

Is there an workable way to extend functionality to allow this, or is this on a road-map for future development ?

### LINKED ISSUE #1348: Insert intermediate pivot table
I would like to insert a table between  Users and  the roles/permissions.
I would like something like this:
user1->new_table1->role1
user1->new_table2->role1
user1->new_table3->role2
Can anyone help me?

### LINKED ISSUE #1353: Assign roles to User from multiple Models' roles
Hi,
so I'm working on a small private project and I'm still relatively new to laravel and web development in general so please bare with me.

My current situation is that I have the standard laravel _User Model_ which can have a corresponding Staff Model which can have a corresponding _Position Model_ (Position as in hierarchical position) and a corresponding _Department Model_. The Staff can be retrieved with a function in the _User_ class, which finds the staff entry in my database by looking for a userID. Then the _Position_ and _Department_ can again be retrieved from the Staff Model with functions.

Now the problem I have is that I don't want to assign those roles manually to each User but to automatically assign specific roles to each user depending on what _Department_ and _Position_ they have.

I would really appreciate if anyone could explain to me how I could get this to work!

EDIT: I just realised what I wrote isn't quite what I meant ^^ What I really want to achieve is not to really assign those roles to the user, but to be able to check if the User has a permission even though the role with the permission is only assigned to the Users‘ _Department_/_Position_ Model and not the User directly.

Here is a diagramm, which I hope makes clear what I mean:

Role Structure

### LINKED ISSUE #1362: User roles/permissions and per-team roles/permissions
I have user roles/permissions up and running fine, I now need to implement a team system.

The premise is that a `User` will have a `Role` named `Member`, which has a `Permission` named `own-teams`. This is the basic implementation of this package, to enforce ACL for `User`'s.

I now need the `User` to create a `Team` (`id=1`). `User` gets automatically assigned a new `TeamRole` named `Owner`, with a `TeamPermission` named `manage-posts`, denoting that this `User` can now make blog posts on behalf of the `Team` he created.

All records of `Role` and `TeamRole` should be separate. eg; The `Owner` `TeamRole` shouldn't show up when managing `Role` records, nor should it show up when managing a `Team` where `id=2`. `TeamPermission` records should be shared across all `TeamRole` records, just like all `Permission` records are shared across all `Role` records.

Is this out of scope for this package or is there a way to have extra ACL systems tacked onto the side?

### LINKED ISSUE #1499: Multi tenant multi database support, tried all but not working.
I tried to extend the models, as well as updating permission config files while switching to tenant database but still when I try to update the role and permissions it does not work and always fetching roles and permissions using default database connection.

```php
<?php

namespace App\Client;

use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    protected $connection = 'client';

    protected $table = 'roles';

    protected $fillable = ['name'];
    
    public function __construct()
    {
        parent::__construct();

        if ($connection = config('permission.db_connection')) {
            $this->setConnection($connection);
        }
    }
}
```

Permission model

```php
<?php

namespace App\Client;

use Spatie\Permission\Models\Permission as ModelsPermission;

class Permission extends ModelsPermission
{
    protected $connection = 'client';

    protected $table = 'permissions';

    protected $fillable = ['name'];

    public function __construct()
    {
        parent::__construct();

        if ($connection = config('permission.db_connection')) {
            $this->setConnection($connection);
        }
    }
}
```

Configuration update while switching to tenant connection

```php
'permission.db_connection' => 'client',
'permission.models.permission' => Permission::class,
 'permission.models.role' => Role::class,
```
Role and permission seeder

```php
<?php

use App\Client\Permission;
use App\Client\Role;
use Illuminate\Database\Seeder;

class ClientRoleAndPermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //add client permissions.
        $client_permissions = [
            'manage properties',
            'manage agents',
        ];

        foreach($client_permissions as $p)
        {
            Permission::firstOrCreate([
                'name' => $p,
                'guard_name' => 'client'
            ]);
        }

        //add client roles and assign general permissions to get start.
        Role::firstOrCreate([
            'name' => 'account manager',
            'guard_name' => 'client'
        ])->givePermissionTo([ 'manage agents']);

    }
}
```

Now when I try to update permission, I receive an error that permission does not exist, It means permissions are still being fetched from the main database.

```php
public function updatePermissions(Request $request)
    {
        $this->validate($request, [
            'role' => 'required|numeric',
        ]);

        $role = Role::findById($request->role);

        return $role->givePermissionTo('manage properties');

        flash()->success('Permissions updated for the <b> ' . $role->name . '</b>');
        return back();
    }
```

### LINKED ISSUE #1629: Permissions on multi-tenancy app
I have a 2 tier tenancy app where a system user can spin up client environments with their own db instances. Based on this implementation, I have created a combo of `Role` + `Permission` models on the `App\Models` and the `App\Tenant\Models` directories respectively. The two `Role` models are extensions of Spatie's `Role` implementation and the two `Permission` models are extensions of `Permission` implementation. The tenant models use `ForTenants` trait that defines the database connection as well as the `$guard_name` property. You can view the Role implementation below (similar approach is followed for `Permission` models).

```
namespace App\Models;

use App\Models\Shared\Role as Shared; // Spatie's Role Model

class Role extends Shared
{}
```

```
namespace App\Tenant\Models;

use App\Models\Shared\Role as Shared; // Spatie's Role Model
use App\Tenant\Traits\ForTenants;


class Role extends Shared
{
    use ForTenants;

    /**
     * @var string
     */
    protected $guard_name = 'tenant';
}
```

Based on the docs, I have to specify the model names in the `permission.php` config in order for the code to know which one to use. The problem as you might have guessed by now is that in order for my implementation to work, I need to support two different model versions depending on the guard and not lock the config by pointing to a specific model version i.e. system or tenant. A solution would have been to update the `permission.models.permission` and `permission.models.role` config values during runtime but that did not work:

```
namespace App\Policies;

use Illuminate\Auth\Access\HandlesAuthorization;

class UserPolicy
{
    use HandlesAuthorization;

    public function __construct()
    {
           $tenant = Auth::guard('tenant')->check();
           config([
            'permission.models.permission' => $tenant ? \App\Tenant\Models\Permission::class : \App\Models\Permission::class,
            'permission.models.role' => $tenant ? \App\Tenant\Models\Role::class : \App\Models\Role::class,
           ]);
    }

    /**
     * Determine if user can see all users.
     *
     * @param \App\Models\Shared\Admin $user
     * @return bool
     */
    public function viewAny($user)
    {
        return $user->can('manage own users');
    }
```

The weird thing is if I try to do a `dd($user->hasPermissionTo('manage own users'));` inside the `viewAny` Policy method, it will show me the following error:
```
There is no permission named `manage own users` for guard `tenant`.
```
and doing `dd($user->permissions);` I get an empty array, but if I do `dd($user->getAllPermissions());` I can see a collection of the permissions attached to the user with the `manage own users` permission being part of it.

Am I missing some important step that I need to take into consideration in order for my approach to work or does the package restrict the usage of only one type of model in the config?

Thanks for the great package!

### LINKED ISSUE #1634: Use This Package for Pivot Table
I have many-to-many relationship (user-team), so a user can join multiple teams and a team can have multiple users, at first I was  adding permissions only in team model, but I need to add it in team-user pivot table through this package, so a user can have different permissions for each team he has joined ? Any Ideas how can I achieve this.

### LINKED ISSUE #1654: Associate a single role to multi-structures
Hi,

i need to associate the user with more structures, and the user role are different for every structures.

**Example:**

USER A => associated to Structure N.1 with profile X,
USER A => associated to Structure N.2 with profile Y,

how can I associate the different profile for each structure? 

Thanks, 
Andrea.

### LINKED ISSUE #1744: Multi-tenancy : Split up Roles and Permissions over Landlord / Tenant database.
Hey all,

This question dangles somewhere between Multi-tenancy and Spatie's roles and permissions.

So the idea is to create a multi-tenant application, this application has FIXED roles and permissions for users. And i want them to be "synced" over all tenants. At first i wast thinking about seeding force seeding the new roles permissions on production but that doesn't seem like a smart approach at all.

My second approach would be to create migrations that manually insert roles and permissions, or revoke delete in the up and down of the migration files. This looks like a better approach then seeding, yet the problem might arise for new tenant apps since all the migrations are done in batch 1 so `migrate:rollback` is a bump on the road.

**Third approach** would be to place all roles and permissions in the Landlord Database, and keeping those up to date with migrations. But i have no clue how to split up everything and dealing with the foreign keys.

Plan would be in the following 

landlord db tables:
permissions, roles_has_permissions

tenant db tables:
roles

...

I got a little further in **Third approach** but kinda hit a brick wall here...

So what i did was:

Split up migration files -> one for landlord :

    <?php
    use Illuminate\Support\Facades\Schema;
    use Illuminate\Database\Schema\Blueprint;
    use Illuminate\Database\Migrations\Migration;
    
    class CreatePermissionTables extends Migration
    {
        /**
         * Run the migrations.
         *
         * @return void
         */
        public function up()
        {
            $tableNames = config('permission.table_names');
    
    
            if (empty($tableNames)) {
                throw new \Exception('Error: config/permission.php not loaded. Run [php artisan config:clear] and try again.');
            }
    
            Schema::create($tableNames['permissions'], function (Blueprint $table) {
                $table->bigIncrements('id');
                $table->string('name',125);       // For MySQL 8.0 use string('name', 125);
                $table->string('guard_name', 125); // For MySQL 8.0 use string('guard_name', 125);
                $table->timestamps();
    
                $table->unique(['name', 'guard_name']);
            });
    
            Schema::create($tableNames['roles'], function (Blueprint $table) {
                $table->bigIncrements('id');
                $table->string('name', 125);       // For MySQL 8.0 use string('name', 125);
                $table->string('guard_name', 125); // For MySQL 8.0 use string('guard_name', 125);
                $table->timestamps();
    
                $table->unique(['name', 'guard_name']);
            });
    
    
    
            Schema::create($tableNames['role_has_permissions'], function (Blueprint $table) use ($tableNames) {
                $table->unsignedBigInteger('permission_id');
                $table->unsignedBigInteger('role_id');
    
                $table->foreign('permission_id')
                    ->references('id')
                    ->on($tableNames['permissions'])
                    ->onDelete('cascade');
    
                $table->foreign('role_id')
                    ->references('id')
                    ->on($tableNames['roles'])
                    ->onDelete('cascade');
    
                $table->primary(['permission_id', 'role_id'], 'role_has_permissions_permission_id_role_id_primary');
            });
    
            app('cache')
                ->store(config('permission.cache.store') != 'default' ? config('permission.cache.store') : null)
                ->forget(config('permission.cache.key'));
        }
    
        /**
         * Reverse the migrations.
         *
         * @return void
         */
        public function down()
        {
            $tableNames = config('permission.table_names');
    
            if (empty($tableNames)) {
                throw new \Exception('Error: config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding, or drop the tables manually.');
            }
    
            Schema::drop($tableNames['role_has_permissions']);
            Schema::drop($tableNames['roles']);
            Schema::drop($tableNames['permissions']);
        }
    }

And one for the tenants:

    use Illuminate\Database\Migrations\Migration;
    use Illuminate\Database\Schema\Blueprint;
    use Illuminate\Support\Facades\DB;
    use Illuminate\Support\Facades\Schema;
    
    class CreateRolesTable extends Migration
    {
        /**
         * Run the migrations.
         *
         * @return void
         */
        public function up()
        {
    
            $tableNames = config('permission.table_names');
            $columnNames = config('permission.column_names');
    
            if (empty($tableNames)) {
                throw new \Exception('Error: config/permission.php not loaded. Run [php artisan config:clear] and try again.');
            }
            //GET THE LANDLORD DATABASE NAME HERE...
            $landlord_db_name = DB::connection('landlord')->getDatabaseName();
    
            Schema::create($tableNames['model_has_permissions'], function (Blueprint $table) use ($tableNames, $columnNames, $landlord_db_name) {
                $table->unsignedBigInteger('permission_id');
    
                $table->string('model_type');
                $table->unsignedBigInteger($columnNames['model_morph_key']);
                $table->index([$columnNames['model_morph_key'], 'model_type'], 'model_has_permissions_model_id_model_type_index');
    
                $table->foreign('permission_id')
                    ->references('id')
                    ->on($landlord_db_name.'.'.$tableNames['permissions']) //SET FK TO LANDLORD DB
                    ->onDelete('cascade');
    
                $table->primary(['permission_id', $columnNames['model_morph_key'], 'model_type'],
                    'model_has_permissions_permission_model_type_primary');
            });
    
            Schema::create($tableNames['model_has_roles'], function (Blueprint $table) use ($tableNames, $columnNames, $landlord_db_name) {
                $table->unsignedBigInteger('role_id');
    
                $table->string('model_type');
                $table->unsignedBigInteger($columnNames['model_morph_key']);
                $table->index([$columnNames['model_morph_key'], 'model_type'], 'model_has_roles_model_id_model_type_index');
    
                $table->foreign('role_id')
                    ->references('id')
                    ->on($landlord_db_name.'.'.$tableNames['roles']) //SET FK TO LANDLORD DB
                    ->onDelete('cascade');
    
                $table->primary(['role_id', $columnNames['model_morph_key'], 'model_type'],
                    'model_has_roles_role_model_type_primary');
            });
        }
    
        /**
         * Reverse the migrations.
         *
         * @return void
         */
        public function down()
        {
            $tableNames = config('permission.table_names');
    
            if (empty($tableNames)) {
                throw new \Exception('Error: config/permission.php not found and defaults could not be merged. Please publish the package configuration before proceeding, or drop the tables manually.');
            }
    
            Schema::drop($tableNames['model_has_roles']);
            Schema::drop($tableNames['model_has_permissions']);
        }
    }

Migration was a great success, added some roles and permissions in landlord database, and added role to a user in the tenant. The relationship is  a success and works.

Landlord tables:
Screenshot 2021-05-19 at 17 55 00

Tenant Tables:

Screenshot 2021-05-19 at 17 57 05

Relations:

Screenshot 2021-05-19 at 21 02 48

Now i've extended the Spatie's Role and Permission model in order to use landlord connection:

TenantRole :

    namespace App\Models;
    
    use Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection;
    use Spatie\Permission\Models\Role;
    
    class TenantRole extends Role
    {
        use UsesLandlordConnection;
    
    }

TenantPermission : 

    namespace App\Models;
    
    use Illuminate\Database\Eloquent\Relations\BelongsToMany;
    use Spatie\Multitenancy\Models\Concerns\UsesLandlordConnection;
    use Spatie\Multitenancy\Models\Tenant;
    use Spatie\Permission\Models\Permission;
    
    class TenantPermission extends Permission
    {
       use UsesLandlordConnection;
    }

Oke everything booted, but i had an error on the permissions guard, DAMN!

I disabled cache for testing purpose ... nothing... alright then moving on...

In my view file i tried to check permissions for the logged in user:

     {{Auth::User()->getPermissionNames()}}

And here is where it all broke down :( 

This is the error i got:

Screenshot 2021-05-19 at 17 08 40

It looks like he's looking for the model_has_permissions table in the landlord database instead of the tenant database, if i remove the  `use UsesLandlordConnection;` from the models it's even deader than dead and he's now looking in the Tenant DB.

Screenshot 2021-05-19 at 17 14 59

So anyone know how i can separate those two things ? since i only have 2 models to work with form spatie package : Role & Permission.

It works like 80% but that extra 20% is gonna whomp me into oblivion isn't it ?

Or should i find a different approach and abandon this road?

Anyway thanks for your feedback

_Originally posted by @BartMommens in https://github.com/spatie/laravel-multitenancy/discussions/244_

### PR DESCRIPTION
**Pull request by erikn69**
##TEAMS FEATURE
-------
**Usage in [docs](https://github.com/erikn69/laravel-permission/blob/teams_feature/docs/basic-usage/teams-permissions.md)**

A **fully backwards compatible** addition to for teams/groups functionality.  I have added the tests and docs for this PR, and i can help to bug's review around it. I have been using this code overriding the methods with custom models for 2 years without problems, now i want to share with everyone.

Teams table must be already migrated on db, and foreign key can be customizable by config file. `team_id` as default. ~~Also, i can improve the upgrade method with another `migration` if necessary~~ (done, added upgrade migration and command `setup-teams`, roles with teams support on command `create-role`).

**Example Communities #1782**:
```php
'teams' => true,
/*
  * Change this if you want to use teams feature and your related model
  * foreign key are other than `team_id`.
  */
'team_foreign_key' => 'community_id',

```
image
Where green tables(`users`, `community_user`, and `communities`) are handled by custom migrations. Only new pivot `community_id` is added to the package migration file.

Closes #1812
Closes #1782
Closes #1743
Closes #1744
Closes #1654
Closes #1629
Closes #1634
Closes #1499
Closes #1362
Closes #1353
Closes #1348
Closes #1187
Closes #1186
Closes #1135
Closes #1067
Closes #551
Closes #540
Closes #8
And many others

##BUGS FIX
-------
~~On tests `*_before_saving_object_doesnt_interfere_with_other_objects`, sqls from first object are executing on second object and try to sync and load relation again~~(#1819)

And other small fixes that i already forget

### CODE REVIEW

**Comment by Restingo** [comment]
Thank you, really nice work! Can you also add a solution for a group of roles? For example one role is Documentcreator and one is Invoicecreator and you can sum them up in the role Accountant?

**Comment by systemsolutionweb** [comment]
@Restingo Why don't just assign Documentcreator and Invoicecreator?

**Comment by Restingo** [comment]
@systemsolutionweb because I've got a lot of roles that are the same for many functions / people and therefore I want to group them together for easy use.

**Comment by erikn69** [comment]
@drbyte ready for review, now `permission:show` supports teams
```
+---------------+----------+-----------+--------------+
|               | Team ID: NULL        | Team ID: 1   |
+---------------+----------+-----------+--------------+
|               | testRole | testRole2 | testRoleTeam |
+---------------+----------+-----------+--------------+
| Edit News     |  ·       |  ·        |  ·           |
```

**Comment by erikn69** [comment]
@drbyte ready for review, now `permission:show` supports teams
```
+---------------+----------+-----------+--------------+--------------+
|               | Team ID: NULL        | Team ID: 1   | Team ID: 2   |
+---------------+----------+-----------+--------------+--------------+
|               | testRole | testRole2 | testRoleTeam | testRoleTeam |
+---------------+----------+-----------+--------------+--------------+
| Edit News     |  ·       |  ·        |  ·           |  ·           |
```

File: database/migrations/add_teams_fields.php.stub [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+                $table->unsignedBigInteger($columnNames['team_foreign_key'])->default('1');;
+                $table->index($columnNames['team_foreign_key'], 'model_has_permissions_team_foreign_key_index');
+
+                $table->dropPrimary();
+                $table->primary([$columnNames['team_foreign_key'], 'permission_id', $columnNames['model_morph_key'], 'model_type'],
+                    'model_has_permissions_permission_model_type_primary');
+            }
+        });
+
+        Schema::table($tableNames['model_has_permissions'], function (Blueprint $table) use ($tableNames, $columnNames) {
```
Comment (haystome) [inline database/migrations/add_teams_fields.php.stub:48]: @erikn69 
model_has_roles NOT model_has_permissions

File: database/migrations/add_teams_fields.php.stub [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+            if (! Schema::hasColumn($tableNames['model_has_permissions'], $columnNames['team_foreign_key'])) {
```
Comment (haystome) [inline database/migrations/add_teams_fields.php.stub:49]:
```suggestion
            if (! Schema::hasColumn($tableNames['model_has_roles'], $columnNames['team_foreign_key'])) {
```

Comment (erikn69) [reply database/migrations/add_teams_fields.php.stub]: Thanks

File: database/migrations/add_teams_fields.php.stub (hunk 1 above)
[the remark this answers is not in the document]
Comment (erikn69) [reply database/migrations/add_teams_fields.php.stub]: Thanks

File: src/Commands/CreateRole.php [hunk 3]
```diff
@@ -5,25 +5,41 @@
...
+            $this->warn("Teams feature disabled, argument --team-id has no efect, try update configuration file or removing --team-id");
+            return;
+        }
+
         $role = $roleClass::findOrCreate($this->argument('name'), $this->argument('guard'));
+        app(PermissionRegistrar::class)->setPermissionsTeamId($teamIdAux);
+
+        $teams_key = PermissionRegistrar::$teamsKey;
+        if (PermissionRegistrar::$teams && $this->option('team-id') && is_null($role->$teams_key)) {
+            $this->warn("Role `{$role->name}` already exists and it's global, argument --team-id has no efect");
```
Comment (drbyte) [inline src/Commands/CreateRole.php:37]:
```suggestion
            $this->warn("Role `{$role->name}` already exists on the global team; argument --team-id has no effect");
```

File: src/Commands/UpgradeForTeams.php [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+
+use Illuminate\Console\Command;
+use Illuminate\Support\Facades\Config;
+
+class UpgradeForTeams extends Command
+{
+
+    protected $signature = 'permission:setup-teams';
+
+    protected $description = 'Setup the teams feature in case it is not used';
```
Comment (drbyte) [inline src/Commands/UpgradeForTeams.php:13]:
```suggestion
    protected $description = 'Setup the teams feature by generating the associated migration.';
```

File: src/Commands/UpgradeForTeams.php [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+
+    protected $migrationSuffix = 'add_teams_fields.php';
+
+    public function handle()
+    {
+        if (!Config::get('permission.teams')) {
+            $this->error('Not enabled teams in your permission.php file.');
```
Comment (drbyte) [inline src/Commands/UpgradeForTeams.php:20]:
```suggestion
            $this->error('Teams feature is disabled in your permission.php file.');
```

File: src/Commands/UpgradeForTeams.php [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+            $this->warn('Please enable the teams propertie in your configuration.');
```
Comment (drbyte) [inline src/Commands/UpgradeForTeams.php:21]:
```suggestion
            $this->warn('Please enable the teams setting in your configuration.');
```

File: src/PermissionRegistrar.php [hunk 7]
```diff
@@ -29,6 +29,15 @@ class PermissionRegistrar
     /** @var \DateInterval|int */
     public static $cacheExpirationTime;
 
+    /** @var string */
```
Comment (drbyte) [inline src/PermissionRegistrar.php:32]:
```suggestion
    /** @var bool */
```

File: src/PermissionRegistrar.php [hunk 8]
```diff
@@ -77,6 +87,21 @@ protected function getCacheStoreFromConfig(): \Illuminate\Contracts\Cache\Reposi
         return $this->cacheManager->store($cacheDriver);
     }
 
+    /**
+     * Set the team id for teams/groups support, this id is gonna be taken for permissions/roles loading
```
Comment (drbyte) [inline src/PermissionRegistrar.php:91]:
```suggestion
     * Set the team id for teams/groups support, this id is used when querying permissions/roles
```

File: src/Traits/HasRoles.php [hunk 9]
```diff
@@ -107,19 +119,30 @@ public function assignRole(...$roles)
...
+            }
             $model->load('roles');
         } else {
             $class = \get_class($model);
 
             $class::saved(
                 function ($object) use ($roles, $model) {
+                    if ($model->getKey() != $object->getKey()) {
+                        return;
+                    }
```
Comment (drbyte) [inline src/Traits/HasRoles.php:145]: Thanks for your detailed description of this bug in the original post. 
Is it possible to move this bug-fix to its own separate PR (both for HasRoles and HasPermissions)? I'd like to merge this fix separately from this Teams feature.

Also, is there another test that should be added to prevent this bug? A few different approaches have been taken to get to this point, including model/object comparisons, and I'd like to make sure we don't re-break things again. Refs: #975 and #1663

**Review by drbyte — CHANGES_REQUESTED** [review]
@erikn69 Thank you for your detailed work on this PR.

I've highlighted a number of minor typographical errors,
and commented about requesting the bugfix to be split to a separate PR.

File: src/Traits/HasRoles.php (hunk 9 above)
Comment (erikn69) [reply src/Traits/HasRoles.php:145]: >model/object comparisons 

That is unnecessary beacuse, `$class::saved` comes from `$class=\get_class($model);`, so model and object always have the same class. i test on mi two aplications and it works, I hope I don't break something, because I recently started checking this code

File: src/Models/Role.php [hunk 10]
```diff
@@ -52,7 +61,7 @@ public function permissions(): BelongsToMany
             config('permission.table_names.role_has_permissions'),
             'role_id',
             'permission_id'
-        );
+        )->select('id', 'name', 'guard_name');
```
Comment (erikn69) [inline src/Models/Role.php:64]: @drbyte I'm not sure about this, maybe is a breaking change if somebody already added custom fields and want to use them, but it get less data to memory(`updated_at`,`created_at`,`deleted_at`, etc properties)

Comment (drbyte) [reply src/Models/Role.php:64]: Yes I guess it could be a breaking change.
However, if they've added custom fields then they've probably also already overridden some of the other methods in this trait, so can easily override this one as well.

Perhaps this isn't necessary in this PR though? Maybe it should be separated for further exploration?  I don't like adding hundreds of configuration-settings but perhaps this is one place where it would be useful?

Comment (erikn69) [reply src/Models/Role.php:64]: >Perhaps this isn't necessary in this PR though?

Not necessary, i can remove that

Comment (erikn69) [reply src/Models/Role.php]: Reverted

**Comment by drbyte** [comment]
@erikn69 Can you review my merge-conflict resolutions?

File: tests/TeamHasPermissionsTest.php [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+namespace Spatie\Permission\Test;
+
+class TeamHasPermissionsTest extends HasPermissionsTest
+{
+    /** @var bool */
+    protected $hasTeams=true;
+
+
+    /** @test */
+    public function it_can_asign_same_and_diferent_permission_on_same_user_on_diferent_teams()
```
Comment (drbyte) [inline tests/TeamHasPermissionsTest.php:12]: "asign" => "assign"
"diferent" => "different"

 (also in other tests/files)

Comment (erikn69) [reply tests/TeamHasPermissionsTest.php:12]: ok, i will fix the branch, sorry for my english 😄

Comment (erikn69) [reply tests/TeamHasPermissionsTest.php]: @drbyte it's done

**Review by drbyte — APPROVED** [review]

**Comment by drbyte** [comment]
Thanks @erikn69 !

**Comment by jame0928** [comment]
Hola, me fuera gustado que se pudiera compartir un mismo rol para diferentes teams. Digamos que tengo un usuario que pertenece a 2 teams, y en ambos team tiene el rol de administrador. Con el modelo actual se tendrian que crear dos roles administrador, 1 para cada team, lo que hace que cada vez que se genere un nuevo team, se tenga que replicar todos los roles con sus permisos, y seria deseable que se pudieran compartir.

**Comment by erikn69** [comment]
@jame0928 si puedes usar el mismo rol en diferentes teams, lee la [documentacion ](https://spatie.be/docs/laravel-permission/v5/basic-usage/teams-permissions#roles-creating)

```php
// with null team_id it creates a global role, global roles can be used from any team and they are unique
Role::create(['name' => 'writer', 'team_id' => null]);
```

Tammbien puedes tener Super Admin lee este comentario https://github.com/spatie/laravel-permission/discussions/1840#discussioncomment-1277282
