### PR TITLE
Avoid loss of all permissions/roles pivots on sync error

### LINKED ISSUE #2339: Syncing an incorrect permission results in loss of all permissions
**Before creating a new bug report**
Please check if there isn't a similar issue on [the issue tracker](https://github.com/spatie/laravel-permission/issues) or in [the discussions](https://github.com/spatie/laravel-permission/discussions).

**Describe the bug**
When using the `syncPermissions` function from the `HasPermissions` trait, providing an accidental wrongly named permission will result in loss of all permissions. This is caused by the fact that `syncPermissions` eagerly removes all existing permissions.

**Versions**
You can use `composer show` to get the version numbers of:
- spatie/laravel-permission package version: `main` at commit 490fa00b0c8286659a534d822f7e74c684c86d27
- illuminate/framework package: N/A

PHP version: any

Database version: N/A

**To Reproduce**
1. Create a model that uses the `HasPermissions` trait
2. Assign some valid permissions to the model
3. Use the `syncPermissions` helper, with a combination of any number of valid permissions and at least one invalid permission
Result: all permissions will be lost on the user

**Example Test**
Here is a link to my Github repo containing a minimal Laravel application which shows my problem:
https://github.com/spatie/laravel-permission/compare/main...jnoordsij:spatie-laravel-permission:permission-sync-fail

**Expected behavior**
Result: the operation fails and the permissions remain the same as before 
OR operation does partial work, removing only those permissions which are not synced.
 

**Proposed (possible) solutions**
1. Use the native Laravel `sync` function with detaching; this does not do a full rollback, but it does ensure only pivots that are no longer present are removed, instead of eagerly removing all of them
2. Copy the behavior of the Laravel `sync` function to achieve something similar here
3. Do a "manual backup" of pre-existing permissions and force restore on error
4. Skip over any non-existing permissions and throw Exception afterwards

### PR DESCRIPTION
**Pull request by erikn69**
Closes #2339

>**Describe the bug**
When using the syncPermissions function from the HasPermissions trait, providing an accidental wrongly named permission will result in loss of all permissions. This is caused by the fact that syncPermissions eagerly removes all existing permissions.
>
>**Steps to reproduce the behavior:**
>Create a model that uses the HasPermissions trait
Assign some valid permissions to the model
Use the syncPermissions helper, with a combination of any number of valid permissions and at least one invalid permission
Result: all permissions will be lost on the user
>
>**Example Test**
Here is a link to my Github repo containing a minimal Laravel application which shows my problem:
https://github.com/spatie/laravel-permission/compare/main...jnoordsij:spatie-laravel-permission:permission-sync-fail

### CODE REVIEW

**Comment by erikn69** [comment]
@drbyte ready for review

File: src/Traits/HasPermissions.php [hunk 1]
```diff
@@ -412,9 +412,11 @@ function ($object) use ($permissions, $model) {
      */
     public function syncPermissions(...$permissions)
     {
+        $this->collectPermissions(...$permissions);
```
Comment (drbyte) [inline src/Traits/HasPermissions.php:415]: Should this be `$permissions = $this->collectPermissions($permission);`?
- assignment of returned value
- and drop the `...` when passing the parameter (also in line 419)

Also in `HasRoles`?

Comment (erikn69) [reply src/Traits/HasPermissions.php:415]: I did think of that, but `collectPermissions` returns an array of ids as keys, example
```php
[
   'id_1' => [], 'id_1' => [], 'id_1' => []
]
```
If i do `$permissions = $this->collectPermissions($permission);` i have to add `array_keys`
```php
public function syncPermissions(...$permissions)
    {
        $permissions = $this->collectPermissions(...$permissions);

        $this->permissions()->detach();

        return $this->givePermissionTo(...array_keys($permissions));
    }

```
Still, that doesn't avoid double `collectPermissions` call


@drbyte **should i make the change?**

Comment (erikn69) [reply src/Traits/HasPermissions.php]: Done

Comment (erikn69) [reply src/Traits/HasPermissions.php]: > value is actually a collection, then when we assign the result and then have to run array_keys against it we lose that, don't we?

Yes, in that specific case.

>So, should we revert that $permissions =  part?

I am open to change what is needed to make it work in the best way, I do?

Comment (drbyte) [reply src/Traits/HasPermissions.php]: Yes let's revert that, and the array_keys.
My apologies for the extra work!

Comment (erikn69) [reply src/Traits/HasPermissions.php]: Don't worry, done

File: src/Traits/HasRoles.php [hunk 2]
```diff
@@ -96,14 +96,13 @@ public function scopeRole(Builder $query, $roles, $guard = null): Builder
...
     /**
-     * Assign the given role to the model.
+     * Returns roles ids as array keys
      *
-     * @param  array|string|int|\Spatie\Permission\Contracts\Role|\Illuminate\Support\Collection  ...$roles
-     * @return $this
+     * @param  array|string|int|\Spatie\Permission\Contracts\Role|\Illuminate\Support\Collection  $roles
      */
-    public function assignRole(...$roles)
+    private function collectRoles(...$roles): array
```
Comment (drbyte) [inline src/Traits/HasRoles.php:103]: in `HasPermissions` the "collect" method was `public`.
I agree with keeping it `private` whenever possible. Should the other be made private too?

Comment (erikn69) [reply src/Traits/HasRoles.php:103]: if it would be the best

File: src/Traits/HasPermissions.php [hunk 3]
```diff
@@ -343,9 +343,8 @@ public function getAllPermissions(): Collection
      * Returns permissions ids as array keys
      *
      * @param  string|int|array|\Spatie\Permission\Contracts\Permission|\Illuminate\Support\Collection  $permissions
-     * @return array
      */
-    public function collectPermissions(...$permissions)
+    private function collectPermissions(...$permissions): array
```
Comment (drbyte) [inline src/Traits/HasPermissions.php:347]: Note: in #2182 when this `collectPermissions()` method was created, it was created by @angeljqv as `public`, but probably should have been `private`.
It was released in `v5.5.7`.

Since it's a breaking change, albeit highly unlikely to affect anyone, we won't backport this to `v5`.

**Comment by drbyte** [comment]
Thanks @erikn69 !

File: src/Traits/HasPermissions.php (hunk 3 above)
Comment (angeljqv) [reply src/Traits/HasPermissions.php:347]: Ok, i did test it, it works correctly for me, seems the right way
